import type { Metadata } from "next";
import { Geist, Geist_Mono,Ubuntu } from "next/font/google";
import { RootProvider } from "fumadocs-ui/provider/next";
import "./globals.css";


import { ViewTransitions } from "next-view-transitions";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-ubuntu",
});

export const metadata: Metadata = {
  title: "ManyUI- A Collection of UI Components",
  description: "Generated by create next app",
};

import { Toaster } from "@/components/ui/sonner";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${ubuntu.variable} antialiased`}
      >
        <RootProvider>
          <ViewTransitions>
            {children}
            <Toaster />
          </ViewTransitions>
        </RootProvider>
      </body>
    </html>
  );
}
